package JerseyBreeze.Entities.Northwind;
// Generated Jun 16, 2013 10:02:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name="Categories"
    ,schema="dbo"
    ,catalog="NorthwindIB"
)
public class Categories  implements java.io.Serializable {


     private int categoryId;
     private String categoryName;
     private String description;
     private byte[] picture;
     private Set productses = new HashSet(0);

    public Categories() {
    }

	
    public Categories(int categoryId, String categoryName) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
    }
    public Categories(int categoryId, String categoryName, String description, byte[] picture, Set productses) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
       this.description = description;
       this.picture = picture;
       this.productses = productses;
    }
   
     @Id 
    
    @Column(name="CategoryID", unique=true, nullable=false)
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }
    
    @Column(name="CategoryName", nullable=false)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    
    @Column(name="Description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="Picture")
    public byte[] getPicture() {
        return this.picture;
    }
    
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="categories")
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }




}


