package JerseyBreeze.Entities.Northwind;
// Generated Jun 16, 2013 10:02:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name="Customers"
    ,schema="dbo"
    ,catalog="NorthwindIB"
)
public class Customers  implements java.io.Serializable {


     private String customerId;
     private String companyName;
     private String contactName;
     private String contactTitle;
     private String address;
     private String city;
     private String region;
     private String postalCode;
     private String country;
     private String phone;
     private String fax;
     private Set customerDemographicses = new HashSet(0);
     private Set orderses = new HashSet(0);

    public Customers() {
    }

	
    public Customers(String customerId, String companyName) {
        this.customerId = customerId;
        this.companyName = companyName;
    }
    public Customers(String customerId, String companyName, String contactName, String contactTitle, String address, String city, String region, String postalCode, String country, String phone, String fax, Set customerDemographicses, Set orderses) {
       this.customerId = customerId;
       this.companyName = companyName;
       this.contactName = contactName;
       this.contactTitle = contactTitle;
       this.address = address;
       this.city = city;
       this.region = region;
       this.postalCode = postalCode;
       this.country = country;
       this.phone = phone;
       this.fax = fax;
       this.customerDemographicses = customerDemographicses;
       this.orderses = orderses;
    }
   
     @Id 
    
    @Column(name="CustomerID", unique=true, nullable=false)
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }
    
    @Column(name="CompanyName", nullable=false)
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    
    @Column(name="ContactName")
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }
    
    @Column(name="ContactTitle")
    public String getContactTitle() {
        return this.contactTitle;
    }
    
    public void setContactTitle(String contactTitle) {
        this.contactTitle = contactTitle;
    }
    
    @Column(name="Address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="City")
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="Region")
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    
    @Column(name="PostalCode")
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    
    @Column(name="Country")
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="Phone")
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    @Column(name="Fax")
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="CustomerCustomerDemo", schema="dbo", catalog="NorthwindIB", joinColumns = { 
        @JoinColumn(name="CustomerID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="CustomerTypeID", nullable=false, updatable=false) })
    public Set getCustomerDemographicses() {
        return this.customerDemographicses;
    }
    
    public void setCustomerDemographicses(Set customerDemographicses) {
        this.customerDemographicses = customerDemographicses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="customers")
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


