package JerseyBreeze.Entities.Northwind;
// Generated Jun 16, 2013 10:02:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * CustomerDemographics generated by hbm2java
 */
@Entity
@Table(name="CustomerDemographics"
    ,schema="dbo"
    ,catalog="NorthwindIB"
)
public class CustomerDemographics  implements java.io.Serializable {


     private String customerTypeId;
     private String customerDesc;
     private Set customerses = new HashSet(0);

    public CustomerDemographics() {
    }

	
    public CustomerDemographics(String customerTypeId) {
        this.customerTypeId = customerTypeId;
    }
    public CustomerDemographics(String customerTypeId, String customerDesc, Set customerses) {
       this.customerTypeId = customerTypeId;
       this.customerDesc = customerDesc;
       this.customerses = customerses;
    }
   
     @Id 
    
    @Column(name="CustomerTypeID", unique=true, nullable=false)
    public String getCustomerTypeId() {
        return this.customerTypeId;
    }
    
    public void setCustomerTypeId(String customerTypeId) {
        this.customerTypeId = customerTypeId;
    }
    
    @Column(name="CustomerDesc")
    public String getCustomerDesc() {
        return this.customerDesc;
    }
    
    public void setCustomerDesc(String customerDesc) {
        this.customerDesc = customerDesc;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="customerDemographicses")
    public Set getCustomerses() {
        return this.customerses;
    }
    
    public void setCustomerses(Set customerses) {
        this.customerses = customerses;
    }




}


