package JerseyBreeze.Entities.Northwind;
// Generated Jun 16, 2013 10:02:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name="Region"
    ,schema="dbo"
    ,catalog="NorthwindIB"
)
public class Region  implements java.io.Serializable {


     private int regionId;
     private String regionDescription;
     private Set territorieses = new HashSet(0);

    public Region() {
    }

	
    public Region(int regionId, String regionDescription) {
        this.regionId = regionId;
        this.regionDescription = regionDescription;
    }
    public Region(int regionId, String regionDescription, Set territorieses) {
       this.regionId = regionId;
       this.regionDescription = regionDescription;
       this.territorieses = territorieses;
    }
   
     @Id 
    
    @Column(name="RegionID", unique=true, nullable=false)
    public int getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(int regionId) {
        this.regionId = regionId;
    }
    
    @Column(name="RegionDescription", nullable=false)
    public String getRegionDescription() {
        return this.regionDescription;
    }
    
    public void setRegionDescription(String regionDescription) {
        this.regionDescription = regionDescription;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="region")
    public Set getTerritorieses() {
        return this.territorieses;
    }
    
    public void setTerritorieses(Set territorieses) {
        this.territorieses = territorieses;
    }




}


