package JerseyBreeze.Entities.Northwind;
// Generated Jun 16, 2013 10:02:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Territories generated by hbm2java
 */
@Entity
@Table(name="Territories"
    ,schema="dbo"
    ,catalog="NorthwindIB"
)
public class Territories  implements java.io.Serializable {


     private String territoryId;
     private Region region;
     private String territoryDescription;
     private Set employeeses = new HashSet(0);

    public Territories() {
    }

	
    public Territories(String territoryId, Region region, String territoryDescription) {
        this.territoryId = territoryId;
        this.region = region;
        this.territoryDescription = territoryDescription;
    }
    public Territories(String territoryId, Region region, String territoryDescription, Set employeeses) {
       this.territoryId = territoryId;
       this.region = region;
       this.territoryDescription = territoryDescription;
       this.employeeses = employeeses;
    }
   
     @Id 
    
    @Column(name="TerritoryID", unique=true, nullable=false)
    public String getTerritoryId() {
        return this.territoryId;
    }
    
    public void setTerritoryId(String territoryId) {
        this.territoryId = territoryId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RegionID", nullable=false)
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
    
    @Column(name="TerritoryDescription", nullable=false)
    public String getTerritoryDescription() {
        return this.territoryDescription;
    }
    
    public void setTerritoryDescription(String territoryDescription) {
        this.territoryDescription = territoryDescription;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="territorieses")
    public Set getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }




}


